name: NametagEdit
main: com.nametagedit.plugin.NametagEdit
version: 4.2.1
authors: [sgtcaze, Cory]
soft-depend: [zPermissions, PermissionsEX, GroupManager, LuckPerms, LibsDisguises, Citizens]
commands:
  ne:
    description: NametagEdit commands
    aliases: [nte, nametagedit]